Added support for macro expansion in benchmark names
google/benchmark pull request #1054
Opened 2020-10-06 12:32 UTC by emmenlau

This PR is a proof-of-concept, not a full implementation. It adds partial support for macro expansion in benchmark names, as outlined in issue #1053.

If this PR should be acceptable, it should be further extended to support more macros, and possible should be applied to internal class names too.

2020-10-06 12:42 UTC, LebedevRI commented
Needs a test

2020-10-06 12:47 UTC, pleroy commented
See my comments in #1053, the year is 2020, I don't see why we would get out of our way for supporting type aliases written using macros.

2020-10-07 12:06 UTC, LebedevRI requested changes
Needs test coverage

2020-10-13 09:32 UTC, LebedevRI commented
I think the seems rather self-contained, but i'd like to see a test to actually confirm what isn't working.

2020-10-13 10:17 UTC, emmenlau commented
Now I understand. I've added commit e2f9d98 `Adding test for defined names in test fixtures` that modifies `test/fixture_test.cc` to use a "defined" name. This is the same behavior as we would like to use, to build various benchmarks based on the same benchmark definition, albeit with different names.

The test compiles and works fine as long as it is used in combination with 54308f9 `include/benchmark/benchmark.h: Added support for macro expansion in benchmark names`. However when you go back one commit, removing the support for defined benchmark names, the build will fail.

Is that helpful? We can wrap all of this in a more suitable way, I'm just trying to illustrate the point.

2020-11-17 21:17 UTC, emmenlau commented
This issue is still in state "changes requested". Are the submitted changes useful or is there something else I should do to move this forward? Thanks for your consideration!

2020-11-17 21:48 UTC, LebedevRI approved these changes
This seems to have slipped through the cracks, sorry about that.
It does seem like that testcase doesn't work without the patch - https://godbolt.org/z/64YWKo.
The change itself looks like a clean improvement to me - i wouldn't imagine
the reverse change be acceptable, one dropping `BENCHMARK_PRIVATE_CONCAT_NAME`.
So this LGTM.

@dominichamon ?

2020-11-19 13:50 UTC, dominichamon commented
@pleroy until we can support building this library as if it's 2020 (including the macro API) i think it's reasonable to support enhancements, especially if they're relatively lightweight.

LGTM, sorry for the delay in reviewing.

2020-11-19 13:50 UTC, merged