[doxygen] Check BENCHMARK_ENABLE_INSTALL was set
google/benchmark pull request #1304
Opened 2021-12-13 19:17 UTC by mtrofin

${targets_export_name} is undefined otherwise.

2021-12-13 19:25 UTC, LebedevRI requested changes
How is this related to Doxygen?

2021-12-13 19:28 UTC, mtrofin commented
> How is this related to Doxygen?

Ah, it's not. I had in mind the top of the `if` condition for some reason.

2021-12-13 19:33 UTC, LebedevRI commented
This is still not _quite_ right.
Please refer to https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#exporting-targets-from-the-build-tree

2021-12-13 19:57 UTC, mtrofin commented
> This is still not _quite_ right. Please refer to https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html#exporting-targets-from-the-build-tree

I see this is also what #1275 tried to address. @LebedevRI, the recommendation in the link is what we're currently doing, but that's not working for the `BENCHMARK_ENABLE_INSTALL=OFF` case. Do you have an idea of what we'd want instead? (sorry, my cmake expertise is very limited)

2021-12-14 09:21 UTC, dominichamon commented
i don't know what's missing either... @LebedevRI did you mean to close this?

2021-12-14 09:46 UTC, dominichamon commented
ah, was this fixed by #1305?

2021-12-14 09:58 UTC, LebedevRI commented
> ah, was this fixed by #1305?

Yep.

2021-12-14 09:58 UTC, closed without merging