ci: add a workflow to test cmake 3.10
google/benchmark pull request #1548
Opened 2023-02-17 23:27 UTC by devjgm

Related to https://github.com/google/benchmark/pull/1544

I followed the pattern of the bazel.yml workflow and copied
the basic cmake commands from the top-level README.md.

2023-02-17 23:31 UTC, devjgm commented
@coryan, JFYI

2023-02-20 11:30 UTC, dmah42 requested changes

2023-02-20 11:30 UTC, dmah42 commented on .github/workflows/cmake.yml
> +        os: [ubuntu-latest, macos-latest]
and windows please :)

https://github.com/google/benchmark/blob/main/.github/workflows/build-and-test.yml is the full cmake CI  action.

2023-02-20 11:30 UTC, dmah42 commented on .github/workflows/cmake.yml
> +      run: cmake -H. -Bbuild -GNinja -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON -DCMAKE_BUILD_TYPE=Release
i wasn't aware Ninja was present on github bots. that's neat :)

2023-02-21 14:26 UTC, closed without merging